services:
  document.api:
    image: ${DOCKER_REGISTRY-}documentapi
    build:
      context: src
      dockerfile: Document/Document.API/Dockerfile
  ocelotapigetways.api:
    image: ${DOCKER_REGISTRY-}ocelotapigetways
    build:
      context: src
      dockerfile: ApiGetways/OcelotApiGetways/Dockerfile
