// <auto-generated />
using System;
using CS004_SwaggerUI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS004_SwaggerUI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250809051826_ChangeNameUserEntity")]
    partial class ChangeNameUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS004_SwaggerUI.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@example.com",
                            PasswordHash = "hashedpassword123",
                            Status = 1,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = "user-002",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@example.com",
                            PasswordHash = "hashedpassword456",
                            Status = 1,
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = "user-003",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.wilson@example.com",
                            PasswordHash = "hashedpassword789",
                            Status = 0,
                            Username = "bob_wilson"
                        },
                        new
                        {
                            Id = "user-004",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.brown@example.com",
                            PasswordHash = "hashedpassword101",
                            Status = 2,
                            Username = "alice_brown"
                        },
                        new
                        {
                            Id = "user-005",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.davis@example.com",
                            PasswordHash = "hashedpassword102",
                            Status = 1,
                            Username = "charlie_davis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
